### ISSUE TITLE
companion git tag v2.3.0 crashes when vicreo is enabled

### ISSUE THREAD

**Issue by lvnilesh** [bitfocus/companion-module-vicreo-hotkey#57]
Install and run companion v.2.3.0
Enable vicreo 
Companion crashes 
see logs below

PS: companion crashes right away if vicreo was already enabled while using a previous version of companion.
```
companion    | Connecting to macintosh:10001...
companion    | connected
companion    | msg undefined
companion    | /root/node_modules/companion-module-vicreo-hotkey/hotkey.js:48
companion    | 		switch (msg.type) {
companion    | 		            ^
companion    | 
companion    | TypeError: Cannot read property 'type' of undefined
companion    |     at instance.processData (/root/node_modules/companion-module-vicreo-hotkey/hotkey.js:48:15)
companion    |     at tcp.<anonymous> (/root/node_modules/companion-module-vicreo-hotkey/hotkey.js:100:10)
companion    |     at tcp.emit (events.js:400:28)
companion    |     at Socket.emit (events.js:400:28)
companion    |     at addChunk (internal/streams/readable.js:293:12)
companion    |     at readableAddChunk (internal/streams/readable.js:267:9)
companion    |     at Socket.Readable.push (internal/streams/readable.js:206:10)
companion    |     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by JeffreyDavidsz** [comment]
Which version of vicreo-listener are you using? I'm unable to reproduce above error

**Comment by JeffreyDavidsz** [comment]
For now I've put in place an extra safety when wrong or old data is being send to companion. My guess is that you are using an older version of the listener. So please upgrade to version 5
